exec-once = qs -c caelestia

exec = hyprctl dispatch submap global
submap = global
$volumeStep = 1

bind = Super, SPACE, global, caelestia:launcher
bindel = , XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ $volumeStep%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown
bindl = , Print, exec, caelestia screenshot  # Full screen capture > clipboard
bind = Super+Shift, S, global, caelestia:screenshotFreeze  # Capture region (freeze)
bind = Super+Shift+Alt, S, global, caelestia:screenshot  # Capture region

# Media
bindl = , XF86AudioNext, global, caelestia:mediaNext
bindl = , XF86AudioPause, global, caelestia:mediaToggle
bindl = , XF86AudioPlay, global, caelestia:mediaToggle
bindl = , XF86AudioPrev, global, caelestia:mediaPrev
