exec-once = wayle shell

$menu = ~/.config/rofi/launcher.sh
bind = SUPER, SPACE, exec, $menu

# needs a way to change brightness elegantly per monitor.
# I think this feature is on the way(le)

bindel = , XF86AudioRaiseVolume, exec, wayle audio output-volume +1 
bindel = , XF86AudioLowerVolume, exec, wayle audio output-volume -1 
bindl = , XF86AudioMute, exec, wayle audio output-mute

bindl = , XF86AudioNext, exec, wayle media next
bindl = , XF86AudioPause, exec, wayle media play-pause
bindl = , XF86AudioPlay, exec, wayle media play-pause
bindl = , XF86AudioPrev, exec, wayle media previous

# SCREENSHOT STUFF
bind = $mainMod SHIFT, S, exec, ~/.config/hypr/scripts/screenshot_region.sh
